# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on: workflow_dispatch

jobs:    
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: Java ${{ matrix.java }} compile
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3.5.2

    - name: Set up JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: ${{ matrix.java }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build koverMergedXmlReport
